Formats enhancement
Black-Kamelia/Sprinkler pull request #70
Opened 2024-05-27 17:59 UTC by ZwenDo

2024-06-02 20:39 UTC, notKamui requested changes

2024-06-02 20:39 UTC, notKamui commented on i18n/src/main/kotlin/com/kamelia/sprinkler/i18n/FormattedValue.kt
> + * formatter on translation call instead of directly put them in the translation string.
putting

2024-06-09 20:21 UTC, notKamui approved these changes

2025-01-26 21:14 UTC, SlamaFR approved these changes

2025-01-26 21:48 UTC, merged